# Generated by Django 5.2.4 on 2025-07-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_news_options_news_image_alter_news_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/photos', verbose_name='Фото')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.news', verbose_name='Новости')),
            ],
            options={
                'verbose_name': 'Фото новостей',
                'verbose_name_plural': 'Фото новостей',
            },
        ),
    ]
