# Generated by Django 5.2.4 on 2025-07-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cetagory_news_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cetagory',
            new_name='Cetegory',
        ),
    ]
