# Generated by Django 5.2.4 on 2025-07-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_cetagory_cetegory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cetegory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
