# Generated by Django 5.2.4 on 2025-07-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='new', to='blog.tag', verbose_name='Теги'),
        ),
    ]
