# Generated by Django 5.2.4 on 2025-07-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_news_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='news', to='blog.tag', verbose_name='Теги'),
        ),
    ]
